version: '3.7'
services:
  web:
    container_name: streamSites_web
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
  db:
    container_name: streamSites_db
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./streamSites-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: streamSites_api
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:5000"
    depends_on:
      - db