version: '3.7'
services:
  web:
    container_name: streamSites_web
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
  api:
    container_name: streamSites_api
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - ./server/data:/app/data/
    ports:
      - "4000:4000"